// AUTO-GENERATED by ffigen - DO NOT EDIT
// Run `./gen_bindings.sh` to regenerate
//
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:wgpu/wgpu_native')
library;

import 'dart:ffi' as ffi;

/// Get the last error message.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> wgpu_get_last_error();

/// Create a wgpu instance.
/// Returns instance handle, or 0 on failure.
@ffi.Native<ffi.Uint64 Function(ffi.Pointer<WGPUInstanceDescriptor>)>()
external int wgpun_CreateInstance(
  ffi.Pointer<WGPUInstanceDescriptor> descriptor,
);

/// Release an instance.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_InstanceRelease(
  int instance,
);

/// Get WGSL language features supported by this instance.
/// Returns a bitmask matching GpuWgslLanguageFeatureName enum order.
@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int wgpun_InstanceGetWGSLLanguageFeatures(
  int instance,
);

/// Request an adapter from an instance.
/// Returns adapter handle, or 0 on failure.
@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPURequestAdapterOptions>)
>()
external int wgpun_InstanceRequestAdapter(
  int instance,
  ffi.Pointer<WGPURequestAdapterOptions> options,
);

/// Release an adapter.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_AdapterRelease(
  int adapter,
);

/// Get adapter info.
@ffi.Native<WGPUAdapterInfo Function(ffi.Uint64)>()
external WGPUAdapterInfo wgpun_AdapterGetInfo(
  int adapter,
);

/// Get adapter limits.
@ffi.Native<WGPUDeviceLimits Function(ffi.Uint64)>()
external WGPUDeviceLimits wgpun_AdapterGetLimits(
  int adapter,
);

/// Get adapter downlevel capability flags as a raw u64 bitmask.
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpun_AdapterGetDownlevelFlags(
  int adapter,
);

/// Get adapter features as a bitmask.
/// Bit positions match GpuFeatureName enum order.
@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int wgpun_AdapterGetFeatures(
  int adapter,
);

/// Request a device from an adapter.
/// Returns device handle, or 0 on failure.
@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUDeviceDescriptor>)
>()
external int wgpun_AdapterRequestDevice(
  int adapter,
  ffi.Pointer<WGPUDeviceDescriptor> descriptor,
);

/// Release a device.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_DeviceRelease(
  int device,
);

/// Get the queue for a device.
/// Returns queue handle (a heap-allocated Arc<Queue> clone).
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpun_DeviceGetQueue(
  int device,
);

/// Poll a device for completed work.
@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint8)>()
external void wgpun_DevicePoll(
  int device,
  int wait,
);

/// Get device features as a bitmask.
/// Bit positions match GpuFeatureName enum order.
@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int wgpun_DeviceGetFeatures(
  int device,
);

/// Get device limits.
@ffi.Native<WGPUDeviceLimits Function(ffi.Uint64)>()
external WGPUDeviceLimits wgpun_DeviceGetLimits(
  int device,
);

/// Pop one captured device error.
/// Returns null if the error queue is empty.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Uint64)>()
external ffi.Pointer<ffi.Char> wgpun_DevicePopError(
  int device,
);

/// Push an error scope onto the device's error scope stack.
/// filter: 1 = Validation, 2 = OutOfMemory, 3 = Internal
@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint32)>()
external void wgpun_DevicePushErrorScope(
  int device,
  int filter,
);

/// Pop the top error scope and return the error type + message.
/// Returns error type: 0 = no error, 1 = Validation, 2 = OutOfMemory, 3 = Internal.
/// If an error was captured, the message is available via wgpun_DevicePopScopeError.
@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int wgpun_DevicePopErrorScope(
  int device,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUBufferDescriptor>)
>()
external int wgpun_DeviceCreateBuffer(
  int device,
  ffi.Pointer<WGPUBufferDescriptor> descriptor,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_BufferRelease(
  int buffer,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
  )
>()
external void wgpun_QueueWriteBuffer(
  int queue,
  int buffer,
  int offset,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external void wgpun_QueueWriteTexture(
  int queue,
  int texture,
  ffi.Pointer<ffi.Uint8> data,
  int data_size,
  int bytes_per_row,
  int width,
  int height,
  int depth_or_array_layers,
  int mip_level,
  int origin_x,
  int origin_y,
  int origin_z,
  int aspect,
  int rows_per_image,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUTextureDescriptor>)
>()
external int wgpun_DeviceCreateTexture(
  int device,
  ffi.Pointer<WGPUTextureDescriptor> descriptor,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Void>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int wgpun_TextureCreateFromMetalTexture(
  int device,
  ffi.Pointer<ffi.Void> mtl_texture_ptr,
  int format,
  int width,
  int height,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int wgpun_TextureCreateFromIOSurface(
  int device,
  int io_surface_id,
  int format,
  int width,
  int height,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Void>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int wgpun_TextureCreateFromAHardwareBuffer(
  int device,
  ffi.Pointer<ffi.Void> ahb,
  int format,
  int width,
  int height,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUTextureViewDescriptor>)
>()
external int wgpun_TextureCreateView(
  int texture,
  ffi.Pointer<WGPUTextureViewDescriptor> descriptor,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_TextureRelease(
  int texture,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_TextureViewRelease(
  int view,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUSamplerDescriptor>)
>()
external int wgpun_DeviceCreateSampler(
  int device,
  ffi.Pointer<WGPUSamplerDescriptor> descriptor,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_SamplerRelease(
  int sampler,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Pointer<ffi.Char>,
  )
>()
external int wgpun_DeviceCreateShaderModule(
  int device,
  ffi.Pointer<ffi.Uint8> source,
  int source_len,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Uint64)>()
external ffi.Pointer<ffi.Char> wgpun_ShaderModuleGetCompilationInfo(
  int module,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_ShaderModuleRelease(
  int module,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUBindGroupLayoutDescriptor>)
>()
external int wgpun_DeviceCreateBindGroupLayout(
  int device,
  ffi.Pointer<WGPUBindGroupLayoutDescriptor> desc,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_BindGroupLayoutRelease(
  int layout,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUBindGroupDescriptor>)
>()
external int wgpun_DeviceCreateBindGroup(
  int device,
  ffi.Pointer<WGPUBindGroupDescriptor> desc,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_BindGroupRelease(
  int group,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUPipelineLayoutDescriptor>)
>()
external int wgpun_DeviceCreatePipelineLayout(
  int device,
  ffi.Pointer<WGPUPipelineLayoutDescriptor> desc,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_PipelineLayoutRelease(
  int layout,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPURenderPipelineDescriptor>)
>()
external int wgpun_DeviceCreateRenderPipeline(
  int device,
  ffi.Pointer<WGPURenderPipelineDescriptor> desc,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64, ffi.Uint32)>()
external int wgpun_RenderPipelineGetBindGroupLayout(
  int pipeline,
  int index,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_RenderPipelineRelease(
  int pipeline,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUComputePipelineDescriptor>)
>()
external int wgpun_DeviceCreateComputePipeline(
  int device,
  ffi.Pointer<WGPUComputePipelineDescriptor> desc,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64, ffi.Uint32)>()
external int wgpun_ComputePipelineGetBindGroupLayout(
  int pipeline,
  int index,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_ComputePipelineRelease(
  int pipeline,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_BindGroupRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_BindGroupLayoutRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_PipelineLayoutRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_RenderPipelineRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_ComputePipelineRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_SamplerRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_ShaderModuleRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_TextureViewRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_BufferRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_TextureRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_QuerySetRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_FenceRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_BufferMappingRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external int wgpun_DeviceCreateCommandEncoder(
  int device,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpun_CommandEncoderFinish(
  int encoder,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external void wgpun_CommandEncoderInsertDebugMarker(
  int encoder,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external void wgpun_CommandEncoderPushDebugGroup(
  int encoder,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_CommandEncoderPopDebugGroup(
  int encoder,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int wgpun_CommandEncoderCopyBufferToBuffer(
  int encoder,
  int source,
  int source_offset,
  int destination,
  int destination_offset,
  int size,
);

@ffi.Native<
  ffi.Uint8 Function(ffi.Uint64, ffi.Uint64, ffi.Uint64, ffi.Uint64)
>()
external int wgpun_CommandEncoderClearBuffer(
  int encoder,
  int buffer,
  int offset,
  int size,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int wgpun_CommandEncoderCopyTextureToBuffer(
  int encoder,
  int texture,
  int buffer,
  int bytes_per_row,
  int rows_per_image,
  int width,
  int height,
  int depth,
  int mip_level,
  int origin_x,
  int origin_y,
  int origin_z,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int wgpun_CommandEncoderCopyBufferToTexture(
  int encoder,
  int buffer,
  int texture,
  int bytes_per_row,
  int rows_per_image,
  int width,
  int height,
  int depth,
  int mip_level,
  int origin_x,
  int origin_y,
  int origin_z,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int wgpun_CommandEncoderCopyTextureToTexture(
  int encoder,
  int src_texture,
  int dst_texture,
  int width,
  int height,
  int depth,
  int src_mip_level,
  int src_origin_x,
  int src_origin_y,
  int src_origin_z,
  int dst_mip_level,
  int dst_origin_x,
  int dst_origin_y,
  int dst_origin_z,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Uint64>, ffi.Uint32)
>()
external void wgpun_QueueSubmit(
  int queue,
  ffi.Pointer<ffi.Uint64> command_buffers,
  int count,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPURenderPassDescriptor>)
>()
external int wgpun_CommandEncoderBeginRenderPass(
  int encoder,
  ffi.Pointer<WGPURenderPassDescriptor> descriptor,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64)>()
external void wgpun_RenderPassEncoderSetPipeline(
  int render_pass,
  int pipeline,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>()
external void wgpun_RenderPassEncoderSetBindGroup(
  int render_pass,
  int index,
  int bind_group,
  ffi.Pointer<ffi.Uint32> dynamic_offsets,
  int dynamic_offset_count,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Uint64, ffi.Uint64, ffi.Uint64)
>()
external void wgpun_RenderPassEncoderSetVertexBuffer(
  int render_pass,
  int slot,
  int buffer,
  int offset,
  int size,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint32, ffi.Uint64, ffi.Uint64)
>()
external void wgpun_RenderPassEncoderSetIndexBuffer(
  int render_pass,
  int buffer,
  int format,
  int offset,
  int size,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Uint32, ffi.Uint32, ffi.Uint32)
>()
external void wgpun_RenderPassEncoderDraw(
  int render_pass,
  int vertex_count,
  int instance_count,
  int first_vertex,
  int first_instance,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
  )
>()
external void wgpun_RenderPassEncoderDrawIndexed(
  int render_pass,
  int index_count,
  int instance_count,
  int first_index,
  int base_vertex,
  int first_instance,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint64, ffi.Uint32)>()
external void wgpun_RenderPassEncoderMultiDrawIndexedIndirect(
  int render_pass,
  int indirect_buffer,
  int indirect_offset,
  int count,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint64)>()
external void wgpun_RenderPassEncoderDrawIndirect(
  int render_pass,
  int indirect_buffer,
  int indirect_offset,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint64)>()
external void wgpun_RenderPassEncoderDrawIndexedIndirect(
  int render_pass,
  int indirect_buffer,
  int indirect_offset,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint32)>()
external void wgpun_RenderPassEncoderBeginOcclusionQuery(
  int render_pass,
  int query_index,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_RenderPassEncoderEndOcclusionQuery(
  int render_pass,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>()
external void wgpun_RenderPassEncoderSetViewport(
  int render_pass,
  double x,
  double y,
  double width,
  double height,
  double min_depth,
  double max_depth,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Uint32, ffi.Uint32, ffi.Uint32)
>()
external void wgpun_RenderPassEncoderSetScissorRect(
  int render_pass,
  int x,
  int y,
  int width,
  int height,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Double, ffi.Double, ffi.Double, ffi.Double)
>()
external void wgpun_RenderPassEncoderSetBlendConstant(
  int render_pass,
  double r,
  double g,
  double b,
  double a,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint32)>()
external void wgpun_RenderPassEncoderSetStencilReference(
  int render_pass,
  int reference,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external void wgpun_RenderPassEncoderInsertDebugMarker(
  int render_pass,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external void wgpun_RenderPassEncoderPushDebugGroup(
  int render_pass,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_RenderPassEncoderPopDebugGroup(
  int render_pass,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Pointer<ffi.Uint8>, ffi.Uint32)
>()
external void wgpun_RenderPassEncoderSetImmediates(
  int render_pass,
  int offset,
  ffi.Pointer<ffi.Uint8> data,
  int data_len,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpun_RenderPassEncoderEnd(
  int render_pass,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<WGPUComputePassDescriptor>)
>()
external int wgpun_CommandEncoderBeginComputePass(
  int encoder,
  ffi.Pointer<WGPUComputePassDescriptor> descriptor,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64)>()
external void wgpun_ComputePassEncoderSetPipeline(
  int compute_pass,
  int pipeline,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>()
external void wgpun_ComputePassEncoderSetBindGroup(
  int compute_pass,
  int index,
  int bind_group,
  ffi.Pointer<ffi.Uint32> dynamic_offsets,
  int dynamic_offset_count,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Uint32, ffi.Uint32)>()
external void wgpun_ComputePassEncoderDispatchWorkgroups(
  int compute_pass,
  int x,
  int y,
  int z,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint64)>()
external void wgpun_ComputePassEncoderDispatchWorkgroupsIndirect(
  int compute_pass,
  int indirect_buffer,
  int indirect_offset,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external void wgpun_ComputePassEncoderInsertDebugMarker(
  int compute_pass,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external void wgpun_ComputePassEncoderPushDebugGroup(
  int compute_pass,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_ComputePassEncoderPopDebugGroup(
  int compute_pass,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Pointer<ffi.Uint8>, ffi.Uint32)
>()
external void wgpun_ComputePassEncoderSetImmediates(
  int compute_pass,
  int offset,
  ffi.Pointer<ffi.Uint8> data,
  int data_len,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpun_ComputePassEncoderEnd(
  int compute_pass,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Pointer<WGPURenderBundleEncoderDescriptor>,
  )
>()
external int wgpun_DeviceCreateRenderBundleEncoder(
  int device,
  ffi.Pointer<WGPURenderBundleEncoderDescriptor> descriptor,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64)>()
external void wgpun_RenderBundleEncoderSetPipeline(
  int encoder,
  int pipeline,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint32>,
    ffi.Uint32,
  )
>()
external void wgpun_RenderBundleEncoderSetBindGroup(
  int encoder,
  int index,
  int bind_group,
  ffi.Pointer<ffi.Uint32> dynamic_offsets,
  int dynamic_offset_count,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Uint64, ffi.Uint64, ffi.Uint64)
>()
external void wgpun_RenderBundleEncoderSetVertexBuffer(
  int encoder,
  int slot,
  int buffer,
  int offset,
  int size,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint32, ffi.Uint64, ffi.Uint64)
>()
external void wgpun_RenderBundleEncoderSetIndexBuffer(
  int encoder,
  int buffer,
  int format,
  int offset,
  int size,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Uint32, ffi.Uint32, ffi.Uint32)
>()
external void wgpun_RenderBundleEncoderDraw(
  int encoder,
  int vertex_count,
  int instance_count,
  int first_vertex,
  int first_instance,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
  )
>()
external void wgpun_RenderBundleEncoderDrawIndexed(
  int encoder,
  int index_count,
  int instance_count,
  int first_index,
  int base_vertex,
  int first_instance,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint64)>()
external void wgpun_RenderBundleEncoderDrawIndirect(
  int encoder,
  int indirect_buffer,
  int indirect_offset,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint64)>()
external void wgpun_RenderBundleEncoderDrawIndexedIndirect(
  int encoder,
  int indirect_buffer,
  int indirect_offset,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Uint32, ffi.Pointer<ffi.Uint8>, ffi.Uint32)
>()
external void wgpun_RenderBundleEncoderSetImmediates(
  int encoder,
  int offset,
  ffi.Pointer<ffi.Uint8> data,
  int data_len,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<ffi.Char>)>()
external int wgpun_RenderBundleEncoderFinish(
  int encoder,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Pointer<ffi.Uint64>, ffi.Uint32)
>()
external void wgpun_RenderPassExecuteBundles(
  int render_pass,
  ffi.Pointer<ffi.Uint64> bundles,
  int count,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_RenderBundleRelease(
  int bundle,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void wgpun_RenderBundleRelease_p(
  ffi.Pointer<ffi.Void> ptr,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external int wgpun_BufferReadSync(
  int device,
  int buffer,
  int offset,
  int size,
  ffi.Pointer<ffi.Uint8> output,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Uint32, ffi.Uint32, ffi.Pointer<ffi.Char>)
>()
external int wgpun_DeviceCreateQuerySet(
  int device,
  int query_type,
  int count,
  ffi.Pointer<ffi.Char> label,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_QuerySetRelease(
  int query_set,
);

@ffi.Native<ffi.Uint8 Function(ffi.Uint64, ffi.Uint64, ffi.Uint32)>()
external int wgpun_CommandEncoderWriteTimestamp(
  int encoder,
  int query_set,
  int query_index,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int wgpun_CommandEncoderResolveQuerySet(
  int encoder,
  int query_set,
  int first_query,
  int query_count,
  int destination,
  int destination_offset,
);

@ffi.Native<ffi.Float Function(ffi.Uint64)>()
external double wgpun_QueueGetTimestampPeriod(
  int queue,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint64,
    ffi.Uint32,
  )
>()
external int wgpun_BufferMapStart(
  int device,
  int buffer,
  int offset,
  int size,
  int mode,
);

@ffi.Native<ffi.Int32 Function(ffi.Uint64)>()
external int wgpun_BufferMapStatus(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Uint64)>()
external ffi.Pointer<ffi.Uint8> wgpun_BufferMapGetPointer(
  int handle,
);

@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Uint64)>()
external ffi.Pointer<ffi.Uint8> wgpun_BufferMapGetPointerMut(
  int handle,
);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpun_BufferMapGetSize(
  int handle,
);

@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64)>()
external void wgpun_BufferUnmap(
  int handle,
  int _original_buffer_id,
);

@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<ffi.Uint64>, ffi.Uint32)
>()
external int wgpun_QueueSubmitFenced(
  int queue,
  ffi.Pointer<ffi.Uint64> command_buffers,
  int count,
);

@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Uint64)>()
external int wgpun_FenceStatus(
  int device,
  int handle,
);

@ffi.Native<ffi.Uint32 Function(ffi.Uint64, ffi.Uint64)>()
external int wgpun_FenceWait(
  int device,
  int handle,
);

@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpun_FenceRelease(
  int handle,
);

/// Create a render surface with platform texture sharing.
/// Returns surface handle, or 0 on failure (check wgpu_get_last_error).
@ffi.Native<ffi.Uint64 Function(ffi.Uint64, ffi.Uint32, ffi.Uint32)>()
external int wgpu_create_surface(
  int device_handle,
  int width,
  int height,
);

/// Stub for non-Android - use wgpu_create_surface instead
@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.Pointer<ffi.Void>, ffi.Uint32, ffi.Uint32)
>()
external int wgpu_create_surface_from_window(
  int _device_handle,
  ffi.Pointer<ffi.Void> _window_ptr,
  int _width,
  int _height,
);

/// Get the platform-specific texture handle for sharing.
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpu_get_surface_handle(
  int surface_id,
);

/// Get the pixel buffer pointer for a surface (Windows only).
@ffi.Native<ffi.Pointer<ffi.Uint8> Function(ffi.Uint64)>()
external ffi.Pointer<ffi.Uint8> wgpu_get_pixel_buffer_ptr(
  int surface_id,
);

/// Get the D3D11 shared handle for a surface (Windows only).
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpu_get_shared_handle(
  int surface_id,
);

/// Get the texture format of a surface (returns FFI texture format value).
@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int wgpu_get_surface_format(
  int surface_id,
);

/// Resize surface. Returns 1 on success, 0 on failure.
@ffi.Native<ffi.Int32 Function(ffi.Uint64, ffi.Uint32, ffi.Uint32)>()
external int wgpu_resize_surface(
  int surface_id,
  int width,
  int height,
);

/// Destroy surface.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpu_destroy_surface(
  int surface_id,
);

@ffi.Native<ffi.Void Function(ffi.Int64, ffi.Int64)>()
external void wgpu_mark_frame_available(
  int _engine_handle,
  int _texture_id,
);

/// Get texture view for rendering to surface.
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpu_surface_get_texture_view(
  int surface_id,
);

/// Copy from a GpuTexture to surface.
@ffi.Native<ffi.Void Function(ffi.Uint64, ffi.Uint64)>()
external void wgpu_surface_copy_from_texture(
  int surface_id,
  int src_texture,
);

/// Signal frame is ready for display.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpu_surface_present(
  int surface_id,
);

/// Stub for unsupported platforms.
@ffi.Native<
  ffi.Uint64 Function(ffi.Uint64, ffi.IntPtr, ffi.Uint32, ffi.Uint32)
>()
external int wgpu_create_swapchain_surface(
  int _device_handle,
  int _native_handle,
  int _width,
  int _height,
);

/// Get the texture format of a swapchain surface.
/// Returns format enum value matching GpuTextureFormat index.
@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>()
external int wgpu_swapchain_get_format(
  int surface_id,
);

/// Acquire the next swapchain texture for rendering.
/// Returns texture view handle, or 0 if failed.
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpu_swapchain_get_texture_view(
  int surface_id,
);

/// Get the depth texture view for a swapchain surface.
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int wgpu_swapchain_get_depth_view(
  int surface_id,
);

/// Present the current swapchain frame.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpu_swapchain_present(
  int surface_id,
);

/// Resize a swapchain surface.
/// Returns 1 on success, 0 on failure.
@ffi.Native<ffi.Uint32 Function(ffi.Uint64, ffi.Uint32, ffi.Uint32)>()
external int wgpu_swapchain_resize(
  int surface_id,
  int width,
  int height,
);

/// Clear the swapchain to a solid color and present.
@ffi.Native<
  ffi.Void Function(ffi.Uint64, ffi.Double, ffi.Double, ffi.Double, ffi.Double)
>()
external void wgpu_swapchain_clear(
  int surface_id,
  double r,
  double g,
  double b,
  double a,
);

/// Destroy a swapchain surface.
@ffi.Native<ffi.Void Function(ffi.Uint64)>()
external void wgpu_swapchain_destroy(
  int surface_id,
);

final class WGPUInstanceDescriptor extends ffi.Struct {
  @ffi.Uint8()
  external int validation;

  @ffi.Uint8()
  external int gpu_based_validation;

  /// Backend bitmask: Vulkan=1, GL=2, Metal=4, DX12=8, BrowserWebGpu=16.
  /// 0 = all backends (default).
  @ffi.Uint32()
  external int backends;
}

final class WGPURequestAdapterOptions extends ffi.Struct {
  @ffi.Uint32()
  external int power_preference;

  @ffi.Uint8()
  external int force_fallback_adapter;
}

final class WGPUAdapterInfo extends ffi.Struct {
  external ffi.Pointer<ffi.Char> vendor;

  external ffi.Pointer<ffi.Char> architecture;

  external ffi.Pointer<ffi.Char> device;

  external ffi.Pointer<ffi.Char> description;

  @ffi.Uint32()
  external int backend_type;

  @ffi.Uint32()
  external int adapter_type;

  @ffi.Uint32()
  external int vendor_id;

  @ffi.Uint32()
  external int device_id;

  /// Vulkan API version (VK_MAKE_API_VERSION packed u32), 0 on non-Vulkan.
  @ffi.Uint32()
  external int driver_api_version;
}

final class WGPUDeviceLimits extends ffi.Struct {
  @ffi.Uint32()
  external int max_texture_dimension_1d;

  @ffi.Uint32()
  external int max_texture_dimension_2d;

  @ffi.Uint32()
  external int max_texture_dimension_3d;

  @ffi.Uint32()
  external int max_texture_array_layers;

  @ffi.Uint32()
  external int max_bind_groups;

  @ffi.Uint32()
  external int max_bind_groups_plus_vertex_buffers;

  @ffi.Uint32()
  external int max_bindings_per_bind_group;

  @ffi.Uint32()
  external int max_dynamic_uniform_buffers_per_pipeline_layout;

  @ffi.Uint32()
  external int max_dynamic_storage_buffers_per_pipeline_layout;

  @ffi.Uint32()
  external int max_sampled_textures_per_shader_stage;

  @ffi.Uint32()
  external int max_samplers_per_shader_stage;

  @ffi.Uint32()
  external int max_storage_buffers_per_shader_stage;

  @ffi.Uint32()
  external int max_storage_textures_per_shader_stage;

  @ffi.Uint32()
  external int max_uniform_buffers_per_shader_stage;

  @ffi.Uint64()
  external int max_uniform_buffer_binding_size;

  @ffi.Uint64()
  external int max_storage_buffer_binding_size;

  @ffi.Uint32()
  external int min_uniform_buffer_offset_alignment;

  @ffi.Uint32()
  external int min_storage_buffer_offset_alignment;

  @ffi.Uint32()
  external int max_vertex_buffers;

  @ffi.Uint64()
  external int max_buffer_size;

  @ffi.Uint32()
  external int max_vertex_attributes;

  @ffi.Uint32()
  external int max_vertex_buffer_array_stride;

  @ffi.Uint32()
  external int max_inter_stage_shader_variables;

  @ffi.Uint32()
  external int max_color_attachments;

  @ffi.Uint32()
  external int max_color_attachment_bytes_per_sample;

  @ffi.Uint32()
  external int max_compute_workgroup_storage_size;

  @ffi.Uint32()
  external int max_compute_invocations_per_workgroup;

  @ffi.Uint32()
  external int max_compute_workgroup_size_x;

  @ffi.Uint32()
  external int max_compute_workgroup_size_y;

  @ffi.Uint32()
  external int max_compute_workgroup_size_z;

  @ffi.Uint32()
  external int max_compute_workgroups_per_dimension;

  /// Maximum size of immediate (push constant) data in bytes (0 = none).
  @ffi.Uint32()
  external int max_immediate_size;
}

final class WGPUDeviceDescriptor extends ffi.Struct {
  /// Bitmask of required features (bit positions match GpuFeatureName enum order).
  @ffi.Uint32()
  external int required_features;

  /// Pointer to required limits, or null for defaults.
  external ffi.Pointer<WGPUDeviceLimits> required_limits;

  /// If non-zero, request bindless texture extensions (wgpu-specific).
  @ffi.Uint8()
  external int bindless_textures;

  /// If non-zero, request IMMEDIATES feature (push constants).
  @ffi.Uint8()
  external int immediates;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUBufferDescriptor extends ffi.Struct {
  @ffi.Uint64()
  external int size;

  @ffi.Uint32()
  external int usage;

  @ffi.Uint8()
  external int mapped_at_creation;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUTextureDescriptor extends ffi.Struct {
  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int depth_or_array_layers;

  @ffi.Uint32()
  external int mip_level_count;

  @ffi.Uint32()
  external int sample_count;

  @ffi.Uint32()
  external int dimension;

  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int usage;

  @ffi.Uint32()
  external int view_format_count;

  external ffi.Pointer<ffi.Uint32> view_formats;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUTextureViewDescriptor extends ffi.Struct {
  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int dimension;

  @ffi.Uint32()
  external int base_mip_level;

  @ffi.Uint32()
  external int mip_level_count;

  @ffi.Uint32()
  external int base_array_layer;

  @ffi.Uint32()
  external int array_layer_count;

  @ffi.Uint32()
  external int aspect;

  /// TextureUsages flags (0 = inherit from texture).
  @ffi.Uint32()
  external int usage;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUSamplerDescriptor extends ffi.Struct {
  @ffi.Uint32()
  external int address_mode_u;

  @ffi.Uint32()
  external int address_mode_v;

  @ffi.Uint32()
  external int address_mode_w;

  @ffi.Uint32()
  external int mag_filter;

  @ffi.Uint32()
  external int min_filter;

  @ffi.Uint32()
  external int mipmap_filter;

  @ffi.Float()
  external double lod_min_clamp;

  @ffi.Float()
  external double lod_max_clamp;

  @ffi.Uint32()
  external int compare;

  @ffi.Uint16()
  external int max_anisotropy;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUBindGroupLayoutEntry extends ffi.Struct {
  @ffi.Uint32()
  external int binding;

  @ffi.Uint32()
  external int visibility;

  @ffi.Uint32()
  external int binding_type;

  @ffi.Uint32()
  external int buffer_type;

  @ffi.Uint8()
  external int has_dynamic_offset;

  @ffi.Uint64()
  external int min_binding_size;

  @ffi.Uint32()
  external int sampler_type;

  @ffi.Uint32()
  external int texture_sample_type;

  @ffi.Uint32()
  external int texture_view_dimension;

  @ffi.Uint8()
  external int texture_multisampled;

  /// Number of elements for binding arrays (0 = not an array).
  @ffi.Uint32()
  external int count;
}

final class WGPUBindGroupLayoutDescriptor extends ffi.Struct {
  external ffi.Pointer<WGPUBindGroupLayoutEntry> entries;

  @ffi.Uint32()
  external int entry_count;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUBindGroupEntry extends ffi.Struct {
  @ffi.Uint32()
  external int binding;

  @ffi.Uint32()
  external int resource_type;

  @ffi.Uint64()
  external int resource;

  @ffi.Uint64()
  external int offset;

  @ffi.Uint64()
  external int size;
}

final class WGPUBindGroupDescriptor extends ffi.Struct {
  @ffi.Uint64()
  external int layout;

  external ffi.Pointer<WGPUBindGroupEntry> entries;

  @ffi.Uint32()
  external int entry_count;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUPipelineLayoutDescriptor extends ffi.Struct {
  external ffi.Pointer<ffi.Uint64> bind_group_layouts;

  @ffi.Uint32()
  external int bind_group_layout_count;

  /// Size in bytes of immediate (push constant) data. 0 = none.
  @ffi.Uint32()
  external int immediate_size;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUVertexAttribute extends ffi.Struct {
  @ffi.Uint32()
  external int format;

  @ffi.Uint64()
  external int offset;

  @ffi.Uint32()
  external int shader_location;
}

final class WGPUVertexBufferLayout extends ffi.Struct {
  @ffi.Uint64()
  external int array_stride;

  @ffi.Uint32()
  external int step_mode;

  external ffi.Pointer<WGPUVertexAttribute> attributes;

  @ffi.Uint32()
  external int attribute_count;
}

final class WGPUVertexState extends ffi.Struct {
  @ffi.Uint64()
  external int module;

  external ffi.Pointer<ffi.Char> entry_point;

  external ffi.Pointer<WGPUVertexBufferLayout> buffers;

  @ffi.Uint32()
  external int buffer_count;

  @ffi.Uint32()
  external int constant_count;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> constant_keys;

  external ffi.Pointer<ffi.Double> constant_values;
}

final class WGPUBlendComponent extends ffi.Struct {
  @ffi.Uint32()
  external int operation;

  @ffi.Uint32()
  external int src_factor;

  @ffi.Uint32()
  external int dst_factor;
}

final class WGPUColorTargetState extends ffi.Struct {
  @ffi.Uint32()
  external int format;

  @ffi.Uint8()
  external int blend_enabled;

  external WGPUBlendComponent blend_color;

  external WGPUBlendComponent blend_alpha;

  @ffi.Uint32()
  external int write_mask;
}

final class WGPUFragmentState extends ffi.Struct {
  @ffi.Uint64()
  external int module;

  external ffi.Pointer<ffi.Char> entry_point;

  external ffi.Pointer<WGPUColorTargetState> targets;

  @ffi.Uint32()
  external int target_count;

  @ffi.Uint32()
  external int constant_count;

  external ffi.Pointer<ffi.Pointer<ffi.Char>> constant_keys;

  external ffi.Pointer<ffi.Double> constant_values;
}

final class WGPUDepthStencilState extends ffi.Struct {
  @ffi.Uint32()
  external int format;

  @ffi.Uint8()
  external int depth_write_enabled;

  @ffi.Uint32()
  external int depth_compare;

  @ffi.Int32()
  external int depth_bias;

  @ffi.Float()
  external double depth_bias_slope_scale;

  @ffi.Float()
  external double depth_bias_clamp;

  @ffi.Uint32()
  external int stencil_front_compare;

  @ffi.Uint32()
  external int stencil_front_fail_op;

  @ffi.Uint32()
  external int stencil_front_depth_fail_op;

  @ffi.Uint32()
  external int stencil_front_pass_op;

  @ffi.Uint32()
  external int stencil_back_compare;

  @ffi.Uint32()
  external int stencil_back_fail_op;

  @ffi.Uint32()
  external int stencil_back_depth_fail_op;

  @ffi.Uint32()
  external int stencil_back_pass_op;

  @ffi.Uint32()
  external int stencil_read_mask;

  @ffi.Uint32()
  external int stencil_write_mask;
}

final class WGPURenderPipelineDescriptor extends ffi.Struct {
  @ffi.Uint64()
  external int layout;

  external WGPUVertexState vertex;

  external WGPUFragmentState fragment;

  @ffi.Uint32()
  external int primitive_topology;

  @ffi.Uint32()
  external int strip_index_format;

  @ffi.Uint32()
  external int front_face;

  @ffi.Uint32()
  external int cull_mode;

  @ffi.Uint8()
  external int unclipped_depth;

  @ffi.Uint8()
  external int depth_stencil_enabled;

  external WGPUDepthStencilState depth_stencil;

  @ffi.Uint32()
  external int multisample_count;

  @ffi.Uint32()
  external int multisample_mask;

  @ffi.Uint8()
  external int alpha_to_coverage_enabled;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUComputePipelineDescriptor extends ffi.Struct {
  @ffi.Uint64()
  external int layout;

  @ffi.Uint64()
  external int module;

  external ffi.Pointer<ffi.Char> entry_point;

  /// Number of pipeline-overridable constants.
  @ffi.Uint32()
  external int constant_count;

  /// Parallel array of constant key C-strings (length = constant_count).
  external ffi.Pointer<ffi.Pointer<ffi.Char>> constant_keys;

  /// Parallel array of constant f64 values (length = constant_count).
  external ffi.Pointer<ffi.Double> constant_values;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPURenderPassColorAttachment extends ffi.Struct {
  @ffi.Uint64()
  external int view;

  @ffi.Uint64()
  external int resolve_target;

  @ffi.Uint32()
  external int load_op;

  @ffi.Uint32()
  external int store_op;

  @ffi.Double()
  external double clear_r;

  @ffi.Double()
  external double clear_g;

  @ffi.Double()
  external double clear_b;

  @ffi.Double()
  external double clear_a;

  /// Depth slice for 3D texture render targets (u32::MAX = None).
  @ffi.Uint32()
  external int depth_slice;
}

final class WGPURenderPassDepthStencilAttachment extends ffi.Struct {
  @ffi.Uint64()
  external int view;

  @ffi.Uint32()
  external int depth_load_op;

  @ffi.Uint32()
  external int depth_store_op;

  @ffi.Float()
  external double depth_clear_value;

  @ffi.Uint8()
  external int depth_read_only;

  @ffi.Uint32()
  external int stencil_load_op;

  @ffi.Uint32()
  external int stencil_store_op;

  @ffi.Uint32()
  external int stencil_clear_value;

  @ffi.Uint8()
  external int stencil_read_only;
}

final class WGPURenderPassDescriptor extends ffi.Struct {
  external ffi.Pointer<WGPURenderPassColorAttachment> color_attachments;

  @ffi.Uint32()
  external int color_attachment_count;

  external ffi.Pointer<WGPURenderPassDepthStencilAttachment>
  depth_stencil_attachment;

  @ffi.Uint64()
  external int occlusion_query_set;

  /// Max draw calls (0 = use default 50_000_000).
  @ffi.Uint64()
  external int max_draw_count;

  /// Timestamp writes query set handle (0 = none).
  @ffi.Uint64()
  external int timestamp_writes_query_set;

  /// Query index for beginning timestamp.
  @ffi.Uint32()
  external int timestamp_writes_beginning;

  /// Query index for end timestamp.
  @ffi.Uint32()
  external int timestamp_writes_end;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPUComputePassDescriptor extends ffi.Struct {
  /// Timestamp writes query set handle (0 = none).
  @ffi.Uint64()
  external int timestamp_writes_query_set;

  /// Query index for beginning timestamp.
  @ffi.Uint32()
  external int timestamp_writes_beginning;

  /// Query index for end timestamp.
  @ffi.Uint32()
  external int timestamp_writes_end;

  external ffi.Pointer<ffi.Char> label;
}

final class WGPURenderBundleEncoderDescriptor extends ffi.Struct {
  external ffi.Pointer<ffi.Uint32> color_formats;

  @ffi.Uint32()
  external int color_format_count;

  @ffi.Uint32()
  external int depth_stencil_format;

  @ffi.Uint32()
  external int sample_count;

  @ffi.Uint8()
  external int depth_read_only;

  @ffi.Uint8()
  external int stencil_read_only;

  external ffi.Pointer<ffi.Char> label;
}
