// wgpu_native - FFI bindings for wgpu
// AUTO-GENERATED by cbindgen - DO NOT EDIT


#ifndef WGPU_NATIVE_H
#define WGPU_NATIVE_H

#include <stdint.h>
#include <stdbool.h>

#define BINDING_TYPE_BUFFER 0

#define BINDING_TYPE_SAMPLER 1

#define BINDING_TYPE_TEXTURE 2

#define BINDING_TYPE_STORAGE_TEXTURE 3

#define MAP_STATUS_PENDING 0

#define MAP_STATUS_READY 1

#define MAP_STATUS_ERROR -1

typedef uint64_t WGPUInstance;

typedef struct WGPUInstanceDescriptor {
  uint8_t validation;
  uint8_t gpu_based_validation;
  /**
   * Backend bitmask: Vulkan=1, GL=2, Metal=4, DX12=8, BrowserWebGpu=16.
   * 0 = all backends (default).
   */
  uint32_t backends;
} WGPUInstanceDescriptor;

typedef uint64_t WGPUAdapter;

typedef struct WGPURequestAdapterOptions {
  uint32_t power_preference;
  uint8_t force_fallback_adapter;
} WGPURequestAdapterOptions;

typedef struct WGPUAdapterInfo {
  const char *vendor;
  const char *architecture;
  const char *device;
  const char *description;
  uint32_t backend_type;
  uint32_t adapter_type;
  uint32_t vendor_id;
  uint32_t device_id;
  /**
   * Vulkan API version (VK_MAKE_API_VERSION packed u32), 0 on non-Vulkan.
   */
  uint32_t driver_api_version;
} WGPUAdapterInfo;

typedef struct WGPUDeviceLimits {
  uint32_t max_texture_dimension_1d;
  uint32_t max_texture_dimension_2d;
  uint32_t max_texture_dimension_3d;
  uint32_t max_texture_array_layers;
  uint32_t max_bind_groups;
  uint32_t max_bind_groups_plus_vertex_buffers;
  uint32_t max_bindings_per_bind_group;
  uint32_t max_dynamic_uniform_buffers_per_pipeline_layout;
  uint32_t max_dynamic_storage_buffers_per_pipeline_layout;
  uint32_t max_sampled_textures_per_shader_stage;
  uint32_t max_samplers_per_shader_stage;
  uint32_t max_storage_buffers_per_shader_stage;
  uint32_t max_storage_textures_per_shader_stage;
  uint32_t max_uniform_buffers_per_shader_stage;
  uint64_t max_uniform_buffer_binding_size;
  uint64_t max_storage_buffer_binding_size;
  uint32_t min_uniform_buffer_offset_alignment;
  uint32_t min_storage_buffer_offset_alignment;
  uint32_t max_vertex_buffers;
  uint64_t max_buffer_size;
  uint32_t max_vertex_attributes;
  uint32_t max_vertex_buffer_array_stride;
  uint32_t max_inter_stage_shader_variables;
  uint32_t max_color_attachments;
  uint32_t max_color_attachment_bytes_per_sample;
  uint32_t max_compute_workgroup_storage_size;
  uint32_t max_compute_invocations_per_workgroup;
  uint32_t max_compute_workgroup_size_x;
  uint32_t max_compute_workgroup_size_y;
  uint32_t max_compute_workgroup_size_z;
  uint32_t max_compute_workgroups_per_dimension;
  /**
   * Maximum size of immediate (push constant) data in bytes (0 = none).
   */
  uint32_t max_immediate_size;
} WGPUDeviceLimits;

typedef uint64_t WGPUDevice;

typedef struct WGPUDeviceDescriptor {
  /**
   * Bitmask of required features (bit positions match GpuFeatureName enum order).
   */
  uint32_t required_features;
  /**
   * Pointer to required limits, or null for defaults.
   */
  const struct WGPUDeviceLimits *required_limits;
  /**
   * If non-zero, request bindless texture extensions (wgpu-specific).
   */
  uint8_t bindless_textures;
  /**
   * If non-zero, request IMMEDIATES feature (push constants).
   */
  uint8_t immediates;
  const char *label;
} WGPUDeviceDescriptor;

typedef uint64_t WGPUQueue;

typedef uint64_t WGPUBuffer;

typedef struct WGPUBufferDescriptor {
  uint64_t size;
  uint32_t usage;
  uint8_t mapped_at_creation;
  const char *label;
} WGPUBufferDescriptor;

typedef uint64_t WGPUTexture;

typedef struct WGPUTextureDescriptor {
  uint32_t width;
  uint32_t height;
  uint32_t depth_or_array_layers;
  uint32_t mip_level_count;
  uint32_t sample_count;
  uint32_t dimension;
  uint32_t format;
  uint32_t usage;
  uint32_t view_format_count;
  const uint32_t *view_formats;
  const char *label;
} WGPUTextureDescriptor;

typedef uint64_t WGPUTextureView;

typedef struct WGPUTextureViewDescriptor {
  uint32_t format;
  uint32_t dimension;
  uint32_t base_mip_level;
  uint32_t mip_level_count;
  uint32_t base_array_layer;
  uint32_t array_layer_count;
  uint32_t aspect;
  /**
   * TextureUsages flags (0 = inherit from texture).
   */
  uint32_t usage;
  const char *label;
} WGPUTextureViewDescriptor;

typedef uint64_t WGPUSampler;

typedef struct WGPUSamplerDescriptor {
  uint32_t address_mode_u;
  uint32_t address_mode_v;
  uint32_t address_mode_w;
  uint32_t mag_filter;
  uint32_t min_filter;
  uint32_t mipmap_filter;
  float lod_min_clamp;
  float lod_max_clamp;
  uint32_t compare;
  uint16_t max_anisotropy;
  const char *label;
} WGPUSamplerDescriptor;

typedef uint64_t WGPUShaderModule;

typedef uint64_t WGPUBindGroupLayout;

typedef struct WGPUBindGroupLayoutEntry {
  uint32_t binding;
  uint32_t visibility;
  uint32_t binding_type;
  uint32_t buffer_type;
  uint8_t has_dynamic_offset;
  uint64_t min_binding_size;
  uint32_t sampler_type;
  uint32_t texture_sample_type;
  uint32_t texture_view_dimension;
  uint8_t texture_multisampled;
  /**
   * Number of elements for binding arrays (0 = not an array).
   */
  uint32_t count;
} WGPUBindGroupLayoutEntry;

typedef struct WGPUBindGroupLayoutDescriptor {
  const struct WGPUBindGroupLayoutEntry *entries;
  uint32_t entry_count;
  const char *label;
} WGPUBindGroupLayoutDescriptor;

typedef uint64_t WGPUBindGroup;

typedef struct WGPUBindGroupEntry {
  uint32_t binding;
  uint32_t resource_type;
  uint64_t resource;
  uint64_t offset;
  uint64_t size;
} WGPUBindGroupEntry;

typedef struct WGPUBindGroupDescriptor {
  WGPUBindGroupLayout layout;
  const struct WGPUBindGroupEntry *entries;
  uint32_t entry_count;
  const char *label;
} WGPUBindGroupDescriptor;

typedef uint64_t WGPUPipelineLayout;

typedef struct WGPUPipelineLayoutDescriptor {
  const WGPUBindGroupLayout *bind_group_layouts;
  uint32_t bind_group_layout_count;
  /**
   * Size in bytes of immediate (push constant) data. 0 = none.
   */
  uint32_t immediate_size;
  const char *label;
} WGPUPipelineLayoutDescriptor;

typedef uint64_t WGPURenderPipeline;

typedef struct WGPUVertexAttribute {
  uint32_t format;
  uint64_t offset;
  uint32_t shader_location;
} WGPUVertexAttribute;

typedef struct WGPUVertexBufferLayout {
  uint64_t array_stride;
  uint32_t step_mode;
  const struct WGPUVertexAttribute *attributes;
  uint32_t attribute_count;
} WGPUVertexBufferLayout;

typedef struct WGPUVertexState {
  WGPUShaderModule module;
  const char *entry_point;
  const struct WGPUVertexBufferLayout *buffers;
  uint32_t buffer_count;
  uint32_t constant_count;
  const char *const *constant_keys;
  const double *constant_values;
} WGPUVertexState;

typedef struct WGPUBlendComponent {
  uint32_t operation;
  uint32_t src_factor;
  uint32_t dst_factor;
} WGPUBlendComponent;

typedef struct WGPUColorTargetState {
  uint32_t format;
  uint8_t blend_enabled;
  struct WGPUBlendComponent blend_color;
  struct WGPUBlendComponent blend_alpha;
  uint32_t write_mask;
} WGPUColorTargetState;

typedef struct WGPUFragmentState {
  WGPUShaderModule module;
  const char *entry_point;
  const struct WGPUColorTargetState *targets;
  uint32_t target_count;
  uint32_t constant_count;
  const char *const *constant_keys;
  const double *constant_values;
} WGPUFragmentState;

typedef struct WGPUDepthStencilState {
  uint32_t format;
  uint8_t depth_write_enabled;
  uint32_t depth_compare;
  int32_t depth_bias;
  float depth_bias_slope_scale;
  float depth_bias_clamp;
  uint32_t stencil_front_compare;
  uint32_t stencil_front_fail_op;
  uint32_t stencil_front_depth_fail_op;
  uint32_t stencil_front_pass_op;
  uint32_t stencil_back_compare;
  uint32_t stencil_back_fail_op;
  uint32_t stencil_back_depth_fail_op;
  uint32_t stencil_back_pass_op;
  uint32_t stencil_read_mask;
  uint32_t stencil_write_mask;
} WGPUDepthStencilState;

typedef struct WGPURenderPipelineDescriptor {
  WGPUPipelineLayout layout;
  struct WGPUVertexState vertex;
  struct WGPUFragmentState fragment;
  uint32_t primitive_topology;
  uint32_t strip_index_format;
  uint32_t front_face;
  uint32_t cull_mode;
  uint8_t unclipped_depth;
  uint8_t depth_stencil_enabled;
  struct WGPUDepthStencilState depth_stencil;
  uint32_t multisample_count;
  uint32_t multisample_mask;
  uint8_t alpha_to_coverage_enabled;
  const char *label;
} WGPURenderPipelineDescriptor;

typedef uint64_t WGPUComputePipeline;

typedef struct WGPUComputePipelineDescriptor {
  WGPUPipelineLayout layout;
  WGPUShaderModule module;
  const char *entry_point;
  /**
   * Number of pipeline-overridable constants.
   */
  uint32_t constant_count;
  /**
   * Parallel array of constant key C-strings (length = constant_count).
   */
  const char *const *constant_keys;
  /**
   * Parallel array of constant f64 values (length = constant_count).
   */
  const double *constant_values;
  const char *label;
} WGPUComputePipelineDescriptor;

typedef uint64_t WGPUCommandEncoder;

typedef uint64_t WGPUCommandBuffer;

typedef uint64_t WGPURenderPassEncoder;

typedef struct WGPURenderPassColorAttachment {
  WGPUTextureView view;
  WGPUTextureView resolve_target;
  uint32_t load_op;
  uint32_t store_op;
  double clear_r;
  double clear_g;
  double clear_b;
  double clear_a;
  /**
   * Depth slice for 3D texture render targets (u32::MAX = None).
   */
  uint32_t depth_slice;
} WGPURenderPassColorAttachment;

typedef struct WGPURenderPassDepthStencilAttachment {
  WGPUTextureView view;
  uint32_t depth_load_op;
  uint32_t depth_store_op;
  float depth_clear_value;
  uint8_t depth_read_only;
  uint32_t stencil_load_op;
  uint32_t stencil_store_op;
  uint32_t stencil_clear_value;
  uint8_t stencil_read_only;
} WGPURenderPassDepthStencilAttachment;

typedef uint64_t WGPUQuerySet;

typedef struct WGPURenderPassDescriptor {
  const struct WGPURenderPassColorAttachment *color_attachments;
  uint32_t color_attachment_count;
  const struct WGPURenderPassDepthStencilAttachment *depth_stencil_attachment;
  WGPUQuerySet occlusion_query_set;
  /**
   * Max draw calls (0 = use default 50_000_000).
   */
  uint64_t max_draw_count;
  /**
   * Timestamp writes query set handle (0 = none).
   */
  WGPUQuerySet timestamp_writes_query_set;
  /**
   * Query index for beginning timestamp.
   */
  uint32_t timestamp_writes_beginning;
  /**
   * Query index for end timestamp.
   */
  uint32_t timestamp_writes_end;
  const char *label;
} WGPURenderPassDescriptor;

typedef uint64_t WGPUComputePassEncoder;

typedef struct WGPUComputePassDescriptor {
  /**
   * Timestamp writes query set handle (0 = none).
   */
  WGPUQuerySet timestamp_writes_query_set;
  /**
   * Query index for beginning timestamp.
   */
  uint32_t timestamp_writes_beginning;
  /**
   * Query index for end timestamp.
   */
  uint32_t timestamp_writes_end;
  const char *label;
} WGPUComputePassDescriptor;

typedef uint64_t WGPURenderBundleEncoder;

typedef struct WGPURenderBundleEncoderDescriptor {
  const uint32_t *color_formats;
  uint32_t color_format_count;
  uint32_t depth_stencil_format;
  uint32_t sample_count;
  uint8_t depth_read_only;
  uint8_t stencil_read_only;
  const char *label;
} WGPURenderBundleEncoderDescriptor;

typedef uint64_t WGPURenderBundle;

typedef uint64_t WGPUBufferMapping;

typedef uint64_t WGPUFence;

/**
 * Get the last error message.
 */
 const char *wgpu_get_last_error(void) ;

/**
 * Create a wgpu instance.
 * Returns instance handle, or 0 on failure.
 */
 WGPUInstance wgpun_CreateInstance(const struct WGPUInstanceDescriptor *descriptor) ;

/**
 * Release an instance.
 */
 void wgpun_InstanceRelease(WGPUInstance instance) ;

/**
 * Get WGSL language features supported by this instance.
 * Returns a bitmask matching GpuWgslLanguageFeatureName enum order.
 */
 uint32_t wgpun_InstanceGetWGSLLanguageFeatures(WGPUInstance instance) ;

/**
 * Request an adapter from an instance.
 * Returns adapter handle, or 0 on failure.
 */

WGPUAdapter wgpun_InstanceRequestAdapter(WGPUInstance instance,
                                         const struct WGPURequestAdapterOptions *options)
;

/**
 * Release an adapter.
 */
 void wgpun_AdapterRelease(WGPUAdapter adapter) ;

/**
 * Get adapter info.
 */
 struct WGPUAdapterInfo wgpun_AdapterGetInfo(WGPUAdapter adapter) ;

/**
 * Get adapter limits.
 */
 struct WGPUDeviceLimits wgpun_AdapterGetLimits(WGPUAdapter adapter) ;

/**
 * Get adapter downlevel capability flags as a raw u64 bitmask.
 */
 uint64_t wgpun_AdapterGetDownlevelFlags(WGPUAdapter adapter) ;

/**
 * Get adapter features as a bitmask.
 * Bit positions match GpuFeatureName enum order.
 */
 uint32_t wgpun_AdapterGetFeatures(WGPUAdapter adapter) ;

/**
 * Request a device from an adapter.
 * Returns device handle, or 0 on failure.
 */

WGPUDevice wgpun_AdapterRequestDevice(WGPUAdapter adapter,
                                      const struct WGPUDeviceDescriptor *descriptor)
;

/**
 * Release a device.
 */
 void wgpun_DeviceRelease(WGPUDevice device) ;

/**
 * Get the queue for a device.
 * Returns queue handle (a heap-allocated Arc<Queue> clone).
 */
 WGPUQueue wgpun_DeviceGetQueue(WGPUDevice device) ;

/**
 * Poll a device for completed work.
 */
 void wgpun_DevicePoll(WGPUDevice device, uint8_t wait) ;

/**
 * Get device features as a bitmask.
 * Bit positions match GpuFeatureName enum order.
 */
 uint32_t wgpun_DeviceGetFeatures(WGPUDevice device) ;

/**
 * Get device limits.
 */
 struct WGPUDeviceLimits wgpun_DeviceGetLimits(WGPUDevice device) ;

/**
 * Pop one captured device error.
 * Returns null if the error queue is empty.
 */
 const char *wgpun_DevicePopError(WGPUDevice device) ;

/**
 * Push an error scope onto the device's error scope stack.
 * filter: 1 = Validation, 2 = OutOfMemory, 3 = Internal
 */
 void wgpun_DevicePushErrorScope(WGPUDevice device, uint32_t filter) ;

/**
 * Pop the top error scope and return the error type + message.
 * Returns error type: 0 = no error, 1 = Validation, 2 = OutOfMemory, 3 = Internal.
 * If an error was captured, the message is available via wgpun_DevicePopScopeError.
 */
 uint32_t wgpun_DevicePopErrorScope(WGPUDevice device) ;


WGPUBuffer wgpun_DeviceCreateBuffer(WGPUDevice device,
                                    const struct WGPUBufferDescriptor *descriptor)
;

 void wgpun_BufferRelease(WGPUBuffer buffer) ;


void wgpun_QueueWriteBuffer(WGPUQueue queue,
                            WGPUBuffer buffer,
                            uint64_t offset,
                            const uint8_t *data,
                            uint64_t size)
;


void wgpun_QueueWriteTexture(WGPUQueue queue,
                             WGPUTexture texture,
                             const uint8_t *data,
                             uint64_t data_size,
                             uint32_t bytes_per_row,
                             uint32_t width,
                             uint32_t height,
                             uint32_t depth_or_array_layers,
                             uint32_t mip_level,
                             uint32_t origin_x,
                             uint32_t origin_y,
                             uint32_t origin_z,
                             uint32_t aspect,
                             uint32_t rows_per_image)
;


WGPUTexture wgpun_DeviceCreateTexture(WGPUDevice device,
                                      const struct WGPUTextureDescriptor *descriptor)
;


WGPUTexture wgpun_TextureCreateFromMetalTexture(WGPUDevice device,
                                                void *mtl_texture_ptr,
                                                uint32_t format,
                                                uint32_t width,
                                                uint32_t height)
;


WGPUTexture wgpun_TextureCreateFromIOSurface(WGPUDevice device,
                                             uint32_t io_surface_id,
                                             uint32_t format,
                                             uint32_t width,
                                             uint32_t height)
;


WGPUTexture wgpun_TextureCreateFromAHardwareBuffer(WGPUDevice device,
                                                   void *ahb,
                                                   uint32_t format,
                                                   uint32_t width,
                                                   uint32_t height)
;


WGPUTextureView wgpun_TextureCreateView(WGPUTexture texture,
                                        const struct WGPUTextureViewDescriptor *descriptor)
;

 void wgpun_TextureRelease(WGPUTexture texture) ;

 void wgpun_TextureViewRelease(WGPUTextureView view) ;


WGPUSampler wgpun_DeviceCreateSampler(WGPUDevice device,
                                      const struct WGPUSamplerDescriptor *descriptor)
;

 void wgpun_SamplerRelease(WGPUSampler sampler) ;


WGPUShaderModule wgpun_DeviceCreateShaderModule(WGPUDevice device,
                                                const uint8_t *source,
                                                uint32_t source_len,
                                                const char *label)
;

 const char *wgpun_ShaderModuleGetCompilationInfo(WGPUShaderModule module) ;

 void wgpun_ShaderModuleRelease(WGPUShaderModule module) ;


WGPUBindGroupLayout wgpun_DeviceCreateBindGroupLayout(WGPUDevice device,
                                                      const struct WGPUBindGroupLayoutDescriptor *desc)
;

 void wgpun_BindGroupLayoutRelease(WGPUBindGroupLayout layout) ;


WGPUBindGroup wgpun_DeviceCreateBindGroup(WGPUDevice device,
                                          const struct WGPUBindGroupDescriptor *desc)
;

 void wgpun_BindGroupRelease(WGPUBindGroup group) ;


WGPUPipelineLayout wgpun_DeviceCreatePipelineLayout(WGPUDevice device,
                                                    const struct WGPUPipelineLayoutDescriptor *desc)
;

 void wgpun_PipelineLayoutRelease(WGPUPipelineLayout layout) ;


WGPURenderPipeline wgpun_DeviceCreateRenderPipeline(WGPUDevice device,
                                                    const struct WGPURenderPipelineDescriptor *desc)
;


WGPUBindGroupLayout wgpun_RenderPipelineGetBindGroupLayout(WGPURenderPipeline pipeline,
                                                           uint32_t index)
;

 void wgpun_RenderPipelineRelease(WGPURenderPipeline pipeline) ;


WGPUComputePipeline wgpun_DeviceCreateComputePipeline(WGPUDevice device,
                                                      const struct WGPUComputePipelineDescriptor *desc)
;


WGPUBindGroupLayout wgpun_ComputePipelineGetBindGroupLayout(WGPUComputePipeline pipeline,
                                                            uint32_t index)
;

 void wgpun_ComputePipelineRelease(WGPUComputePipeline pipeline) ;

 void wgpun_BindGroupRelease_p(void *ptr) ;

 void wgpun_BindGroupLayoutRelease_p(void *ptr) ;

 void wgpun_PipelineLayoutRelease_p(void *ptr) ;

 void wgpun_RenderPipelineRelease_p(void *ptr) ;

 void wgpun_ComputePipelineRelease_p(void *ptr) ;

 void wgpun_SamplerRelease_p(void *ptr) ;

 void wgpun_ShaderModuleRelease_p(void *ptr) ;

 void wgpun_TextureViewRelease_p(void *ptr) ;

 void wgpun_BufferRelease_p(void *ptr) ;

 void wgpun_TextureRelease_p(void *ptr) ;

 void wgpun_QuerySetRelease_p(void *ptr) ;

 void wgpun_FenceRelease_p(void *ptr) ;

 void wgpun_BufferMappingRelease_p(void *ptr) ;

 WGPUCommandEncoder wgpun_DeviceCreateCommandEncoder(WGPUDevice device, const char *label) ;

 WGPUCommandBuffer wgpun_CommandEncoderFinish(WGPUCommandEncoder encoder) ;

 void wgpun_CommandEncoderInsertDebugMarker(WGPUCommandEncoder encoder, const char *label) ;

 void wgpun_CommandEncoderPushDebugGroup(WGPUCommandEncoder encoder, const char *label) ;

 void wgpun_CommandEncoderPopDebugGroup(WGPUCommandEncoder encoder) ;


uint8_t wgpun_CommandEncoderCopyBufferToBuffer(WGPUCommandEncoder encoder,
                                               WGPUBuffer source,
                                               uint64_t source_offset,
                                               WGPUBuffer destination,
                                               uint64_t destination_offset,
                                               uint64_t size)
;


uint8_t wgpun_CommandEncoderClearBuffer(WGPUCommandEncoder encoder,
                                        WGPUBuffer buffer,
                                        uint64_t offset,
                                        uint64_t size)
;


uint8_t wgpun_CommandEncoderCopyTextureToBuffer(WGPUCommandEncoder encoder,
                                                WGPUTexture texture,
                                                WGPUBuffer buffer,
                                                uint32_t bytes_per_row,
                                                uint32_t rows_per_image,
                                                uint32_t width,
                                                uint32_t height,
                                                uint32_t depth,
                                                uint32_t mip_level,
                                                uint32_t origin_x,
                                                uint32_t origin_y,
                                                uint32_t origin_z)
;


uint8_t wgpun_CommandEncoderCopyBufferToTexture(WGPUCommandEncoder encoder,
                                                WGPUBuffer buffer,
                                                WGPUTexture texture,
                                                uint32_t bytes_per_row,
                                                uint32_t rows_per_image,
                                                uint32_t width,
                                                uint32_t height,
                                                uint32_t depth,
                                                uint32_t mip_level,
                                                uint32_t origin_x,
                                                uint32_t origin_y,
                                                uint32_t origin_z)
;


uint8_t wgpun_CommandEncoderCopyTextureToTexture(WGPUCommandEncoder encoder,
                                                 WGPUTexture src_texture,
                                                 WGPUTexture dst_texture,
                                                 uint32_t width,
                                                 uint32_t height,
                                                 uint32_t depth,
                                                 uint32_t src_mip_level,
                                                 uint32_t src_origin_x,
                                                 uint32_t src_origin_y,
                                                 uint32_t src_origin_z,
                                                 uint32_t dst_mip_level,
                                                 uint32_t dst_origin_x,
                                                 uint32_t dst_origin_y,
                                                 uint32_t dst_origin_z)
;

 void wgpun_QueueSubmit(WGPUQueue queue, const WGPUCommandBuffer *command_buffers, uint32_t count) ;


WGPURenderPassEncoder wgpun_CommandEncoderBeginRenderPass(WGPUCommandEncoder encoder,
                                                          const struct WGPURenderPassDescriptor *descriptor)
;


void wgpun_RenderPassEncoderSetPipeline(WGPURenderPassEncoder render_pass,
                                        WGPURenderPipeline pipeline)
;


void wgpun_RenderPassEncoderSetBindGroup(WGPURenderPassEncoder render_pass,
                                         uint32_t index,
                                         WGPUBindGroup bind_group,
                                         const uint32_t *dynamic_offsets,
                                         uint32_t dynamic_offset_count)
;


void wgpun_RenderPassEncoderSetVertexBuffer(WGPURenderPassEncoder render_pass,
                                            uint32_t slot,
                                            WGPUBuffer buffer,
                                            uint64_t offset,
                                            uint64_t size)
;


void wgpun_RenderPassEncoderSetIndexBuffer(WGPURenderPassEncoder render_pass,
                                           WGPUBuffer buffer,
                                           uint32_t format,
                                           uint64_t offset,
                                           uint64_t size)
;


void wgpun_RenderPassEncoderDraw(WGPURenderPassEncoder render_pass,
                                 uint32_t vertex_count,
                                 uint32_t instance_count,
                                 uint32_t first_vertex,
                                 uint32_t first_instance)
;


void wgpun_RenderPassEncoderDrawIndexed(WGPURenderPassEncoder render_pass,
                                        uint32_t index_count,
                                        uint32_t instance_count,
                                        uint32_t first_index,
                                        int32_t base_vertex,
                                        uint32_t first_instance)
;


void wgpun_RenderPassEncoderMultiDrawIndexedIndirect(WGPURenderPassEncoder render_pass,
                                                     WGPUBuffer indirect_buffer,
                                                     uint64_t indirect_offset,
                                                     uint32_t count)
;


void wgpun_RenderPassEncoderDrawIndirect(WGPURenderPassEncoder render_pass,
                                         WGPUBuffer indirect_buffer,
                                         uint64_t indirect_offset)
;


void wgpun_RenderPassEncoderDrawIndexedIndirect(WGPURenderPassEncoder render_pass,
                                                WGPUBuffer indirect_buffer,
                                                uint64_t indirect_offset)
;


void wgpun_RenderPassEncoderBeginOcclusionQuery(WGPURenderPassEncoder render_pass,
                                                uint32_t query_index)
;

 void wgpun_RenderPassEncoderEndOcclusionQuery(WGPURenderPassEncoder render_pass) ;


void wgpun_RenderPassEncoderSetViewport(WGPURenderPassEncoder render_pass,
                                        float x,
                                        float y,
                                        float width,
                                        float height,
                                        float min_depth,
                                        float max_depth)
;


void wgpun_RenderPassEncoderSetScissorRect(WGPURenderPassEncoder render_pass,
                                           uint32_t x,
                                           uint32_t y,
                                           uint32_t width,
                                           uint32_t height)
;


void wgpun_RenderPassEncoderSetBlendConstant(WGPURenderPassEncoder render_pass,
                                             double r,
                                             double g,
                                             double b,
                                             double a)
;


void wgpun_RenderPassEncoderSetStencilReference(WGPURenderPassEncoder render_pass,
                                                uint32_t reference)
;


void wgpun_RenderPassEncoderInsertDebugMarker(WGPURenderPassEncoder render_pass,
                                              const char *label)
;

 void wgpun_RenderPassEncoderPushDebugGroup(WGPURenderPassEncoder render_pass, const char *label) ;

 void wgpun_RenderPassEncoderPopDebugGroup(WGPURenderPassEncoder render_pass) ;


void wgpun_RenderPassEncoderSetImmediates(WGPURenderPassEncoder render_pass,
                                          uint32_t offset,
                                          const uint8_t *data,
                                          uint32_t data_len)
;

 WGPUCommandEncoder wgpun_RenderPassEncoderEnd(WGPURenderPassEncoder render_pass) ;


WGPUComputePassEncoder wgpun_CommandEncoderBeginComputePass(WGPUCommandEncoder encoder,
                                                            const struct WGPUComputePassDescriptor *descriptor)
;


void wgpun_ComputePassEncoderSetPipeline(WGPUComputePassEncoder compute_pass,
                                         WGPUComputePipeline pipeline)
;


void wgpun_ComputePassEncoderSetBindGroup(WGPUComputePassEncoder compute_pass,
                                          uint32_t index,
                                          WGPUBindGroup bind_group,
                                          const uint32_t *dynamic_offsets,
                                          uint32_t dynamic_offset_count)
;


void wgpun_ComputePassEncoderDispatchWorkgroups(WGPUComputePassEncoder compute_pass,
                                                uint32_t x,
                                                uint32_t y,
                                                uint32_t z)
;


void wgpun_ComputePassEncoderDispatchWorkgroupsIndirect(WGPUComputePassEncoder compute_pass,
                                                        WGPUBuffer indirect_buffer,
                                                        uint64_t indirect_offset)
;


void wgpun_ComputePassEncoderInsertDebugMarker(WGPUComputePassEncoder compute_pass,
                                               const char *label)
;


void wgpun_ComputePassEncoderPushDebugGroup(WGPUComputePassEncoder compute_pass,
                                            const char *label)
;

 void wgpun_ComputePassEncoderPopDebugGroup(WGPUComputePassEncoder compute_pass) ;


void wgpun_ComputePassEncoderSetImmediates(WGPUComputePassEncoder compute_pass,
                                           uint32_t offset,
                                           const uint8_t *data,
                                           uint32_t data_len)
;

 WGPUCommandEncoder wgpun_ComputePassEncoderEnd(WGPUComputePassEncoder compute_pass) ;


WGPURenderBundleEncoder wgpun_DeviceCreateRenderBundleEncoder(WGPUDevice device,
                                                              const struct WGPURenderBundleEncoderDescriptor *descriptor)
;


void wgpun_RenderBundleEncoderSetPipeline(WGPURenderBundleEncoder encoder,
                                          WGPURenderPipeline pipeline)
;


void wgpun_RenderBundleEncoderSetBindGroup(WGPURenderBundleEncoder encoder,
                                           uint32_t index,
                                           WGPUBindGroup bind_group,
                                           const uint32_t *dynamic_offsets,
                                           uint32_t dynamic_offset_count)
;


void wgpun_RenderBundleEncoderSetVertexBuffer(WGPURenderBundleEncoder encoder,
                                              uint32_t slot,
                                              WGPUBuffer buffer,
                                              uint64_t offset,
                                              uint64_t size)
;


void wgpun_RenderBundleEncoderSetIndexBuffer(WGPURenderBundleEncoder encoder,
                                             WGPUBuffer buffer,
                                             uint32_t format,
                                             uint64_t offset,
                                             uint64_t size)
;


void wgpun_RenderBundleEncoderDraw(WGPURenderBundleEncoder encoder,
                                   uint32_t vertex_count,
                                   uint32_t instance_count,
                                   uint32_t first_vertex,
                                   uint32_t first_instance)
;


void wgpun_RenderBundleEncoderDrawIndexed(WGPURenderBundleEncoder encoder,
                                          uint32_t index_count,
                                          uint32_t instance_count,
                                          uint32_t first_index,
                                          int32_t base_vertex,
                                          uint32_t first_instance)
;


void wgpun_RenderBundleEncoderDrawIndirect(WGPURenderBundleEncoder encoder,
                                           WGPUBuffer indirect_buffer,
                                           uint64_t indirect_offset)
;


void wgpun_RenderBundleEncoderDrawIndexedIndirect(WGPURenderBundleEncoder encoder,
                                                  WGPUBuffer indirect_buffer,
                                                  uint64_t indirect_offset)
;


void wgpun_RenderBundleEncoderSetImmediates(WGPURenderBundleEncoder encoder,
                                            uint32_t offset,
                                            const uint8_t *data,
                                            uint32_t data_len)
;


WGPURenderBundle wgpun_RenderBundleEncoderFinish(WGPURenderBundleEncoder encoder,
                                                 const char *label)
;


void wgpun_RenderPassExecuteBundles(WGPURenderPassEncoder render_pass,
                                    const WGPURenderBundle *bundles,
                                    uint32_t count)
;

 void wgpun_RenderBundleRelease(WGPURenderBundle bundle) ;

 void wgpun_RenderBundleRelease_p(void *ptr) ;


uint64_t wgpun_BufferReadSync(WGPUDevice device,
                              WGPUBuffer buffer,
                              uint64_t offset,
                              uint64_t size,
                              uint8_t *output)
;


WGPUQuerySet wgpun_DeviceCreateQuerySet(WGPUDevice device,
                                        uint32_t query_type,
                                        uint32_t count,
                                        const char *label)
;

 void wgpun_QuerySetRelease(WGPUQuerySet query_set) ;


uint8_t wgpun_CommandEncoderWriteTimestamp(WGPUCommandEncoder encoder,
                                           WGPUQuerySet query_set,
                                           uint32_t query_index)
;


uint8_t wgpun_CommandEncoderResolveQuerySet(WGPUCommandEncoder encoder,
                                            WGPUQuerySet query_set,
                                            uint32_t first_query,
                                            uint32_t query_count,
                                            WGPUBuffer destination,
                                            uint64_t destination_offset)
;

 float wgpun_QueueGetTimestampPeriod(WGPUQueue queue) ;


WGPUBufferMapping wgpun_BufferMapStart(WGPUDevice device,
                                       WGPUBuffer buffer,
                                       uint64_t offset,
                                       uint64_t size,
                                       uint32_t mode)
;

 int32_t wgpun_BufferMapStatus(WGPUBufferMapping handle) ;

 const uint8_t *wgpun_BufferMapGetPointer(WGPUBufferMapping handle) ;

 uint8_t *wgpun_BufferMapGetPointerMut(WGPUBufferMapping handle) ;

 uint64_t wgpun_BufferMapGetSize(WGPUBufferMapping handle) ;

 void wgpun_BufferUnmap(WGPUBufferMapping handle, WGPUBuffer _original_buffer_id) ;


WGPUFence wgpun_QueueSubmitFenced(WGPUQueue queue,
                                  const WGPUCommandBuffer *command_buffers,
                                  uint32_t count)
;

 int32_t wgpun_FenceStatus(WGPUDevice device, WGPUFence handle) ;

 uint32_t wgpun_FenceWait(WGPUDevice device, WGPUFence handle) ;

 void wgpun_FenceRelease(WGPUFence handle) ;

#if !defined(TARGET_ANDROID)
/**
 * Create a render surface with platform texture sharing.
 * Returns surface handle, or 0 on failure (check wgpu_get_last_error).
 */
 uint64_t wgpu_create_surface(WGPUDevice device_handle, uint32_t width, uint32_t height) ;
#endif

#if defined(TARGET_ANDROID)
/**
 * Create a render surface from a native window (Android only).
 */

uint64_t wgpu_create_surface_from_window(WGPUDevice device_handle,
                                         void *window_ptr,
                                         uint32_t width,
                                         uint32_t height)
;
#endif

#if defined(TARGET_ANDROID)
/**
 * Stub for Android - use wgpu_create_surface_from_window instead
 */
 uint64_t wgpu_create_surface(WGPUDevice _device_handle, uint32_t _width, uint32_t _height) ;
#endif

#if !defined(TARGET_ANDROID)
/**
 * Stub for non-Android - use wgpu_create_surface instead
 */

uint64_t wgpu_create_surface_from_window(WGPUDevice _device_handle,
                                         void *_window_ptr,
                                         uint32_t _width,
                                         uint32_t _height)
;
#endif

/**
 * Get the platform-specific texture handle for sharing.
 */
 uint64_t wgpu_get_surface_handle(uint64_t surface_id) ;

/**
 * Get the pixel buffer pointer for a surface (Windows only).
 */
 const uint8_t *wgpu_get_pixel_buffer_ptr(uint64_t surface_id) ;

/**
 * Get the D3D11 shared handle for a surface (Windows only).
 */
 uint64_t wgpu_get_shared_handle(uint64_t surface_id) ;

/**
 * Get the texture format of a surface (returns FFI texture format value).
 */
 uint32_t wgpu_get_surface_format(uint64_t surface_id) ;

/**
 * Resize surface. Returns 1 on success, 0 on failure.
 */
 int32_t wgpu_resize_surface(uint64_t surface_id, uint32_t width, uint32_t height) ;

/**
 * Destroy surface.
 */
 void wgpu_destroy_surface(uint64_t surface_id) ;

#if defined(TARGET_APPLE)
 void wgpu_mark_frame_available(int64_t engine_handle, int64_t texture_id) ;
#endif

#if !defined(TARGET_APPLE)
 void wgpu_mark_frame_available(int64_t _engine_handle, int64_t _texture_id) ;
#endif

/**
 * Get texture view for rendering to surface.
 */
 WGPUTextureView wgpu_surface_get_texture_view(uint64_t surface_id) ;

/**
 * Copy from a GpuTexture to surface.
 */
 void wgpu_surface_copy_from_texture(uint64_t surface_id, WGPUTexture src_texture) ;

/**
 * Signal frame is ready for display.
 */
 void wgpu_surface_present(uint64_t surface_id) ;

#if defined(TARGET_WINDOWS)
/**
 * Create a swapchain surface from a native window handle.
 * - Windows: pass HWND
 * - macOS: pass NSWindow pointer (contentView is extracted internally)
 * Returns surface handle, or 0 on failure (check wgpu_get_last_error).
 */

uint64_t wgpu_create_swapchain_surface(WGPUDevice device_handle,
                                       intptr_t native_handle,
                                       uint32_t width,
                                       uint32_t height)
;
#endif

#if !defined(TARGET_WINDOWS)
/**
 * Stub for unsupported platforms.
 */

uint64_t wgpu_create_swapchain_surface(WGPUDevice _device_handle,
                                       intptr_t _native_handle,
                                       uint32_t _width,
                                       uint32_t _height)
;
#endif

/**
 * Get the texture format of a swapchain surface.
 * Returns format enum value matching GpuTextureFormat index.
 */
 uint32_t wgpu_swapchain_get_format(uint64_t surface_id) ;

/**
 * Acquire the next swapchain texture for rendering.
 * Returns texture view handle, or 0 if failed.
 */
 WGPUTextureView wgpu_swapchain_get_texture_view(uint64_t surface_id) ;

/**
 * Get the depth texture view for a swapchain surface.
 */
 WGPUTextureView wgpu_swapchain_get_depth_view(uint64_t surface_id) ;

/**
 * Present the current swapchain frame.
 */
 void wgpu_swapchain_present(uint64_t surface_id) ;

/**
 * Resize a swapchain surface.
 * Returns 1 on success, 0 on failure.
 */
 uint32_t wgpu_swapchain_resize(uint64_t surface_id, uint32_t width, uint32_t height) ;

/**
 * Clear the swapchain to a solid color and present.
 */
 void wgpu_swapchain_clear(uint64_t surface_id, double r, double g, double b, double a) ;

/**
 * Destroy a swapchain surface.
 */
 void wgpu_swapchain_destroy(uint64_t surface_id) ;

#endif  /* WGPU_NATIVE_H */
