import 'dart:ffi';
import 'package:ffi/ffi.dart';
import 'package:gpuweb/gpuweb.dart';
import '../wgpu_ffi.dart' show wgpuLastError;
import 'device.dart';
import 'ffi/bindings_generated.dart' as ffi;
import 'ffi/enum_ffi.dart';
import 'resource.dart';

/// Manually-declared FFI binding for the AHardwareBuffer import symbol.
///
/// The auto-generated bindings file is regenerated by `gen_bindings.sh`; until
/// the binding-gen run picks this up we declare it inline so the Android
/// factory below has something to call.
@Native<
  Uint64 Function(Uint64, Pointer<Void>, Uint32, Uint32, Uint32)
>(symbol: 'wgpun_DeviceImportAHardwareBuffer', assetId: 'package:wgpu/wgpu_native')
external int _wgpunDeviceImportAHardwareBuffer(
  int device,
  Pointer<Void> ahb,
  int width,
  int height,
  int format,
);

/// A GPU texture.
class WgpuTexture extends WgpuNativeResource implements GpuTexture {
  static final _fin = NativeFinalizer(
    Native.addressOf<NativeFunction<Void Function(Pointer<Void>)>>(
      ffi.wgpun_TextureRelease_p,
    ),
  );

  @override
  String label;
  @override
  final int width;
  @override
  final int height;
  @override
  final int depthOrArrayLayers;
  @override
  final GpuTextureDimension dimension;
  @override
  final GpuTextureFormat format;
  @override
  final int usage;
  @override
  final int mipLevelCount;
  @override
  final int sampleCount;

  final GpuTextureViewDimension? _textureBindingViewDimension;

  @override
  GpuTextureViewDimension get textureBindingViewDimension =>
      _textureBindingViewDimension ??
      switch (dimension) {
        GpuTextureDimension.d1 => GpuTextureViewDimension.d1,
        GpuTextureDimension.d3 => GpuTextureViewDimension.d3,
        GpuTextureDimension.d2 =>
          depthOrArrayLayers > 1
              ? GpuTextureViewDimension.d2Array
              : GpuTextureViewDimension.d2,
      };

  WgpuTexture.internal(
    int handle, {
    required this.width,
    required this.height,
    required this.depthOrArrayLayers,
    this.dimension = GpuTextureDimension.d2,
    required this.format,
    required this.usage,
    required this.mipLevelCount,
    this.sampleCount = 1,
    this.label = '',
    GpuTextureViewDimension? textureBindingViewDimension,
  }) : _textureBindingViewDimension = textureBindingViewDimension,
       super(handle, _fin);

  int get handle => nativeHandle;

  @override
  NativeFinalizer get finalizer => _fin;
  @override
  void release(int handle) => ffi.wgpun_TextureRelease(handle);

  /// Import an `AHardwareBuffer*` (Android) as a `WgpuTexture`.
  ///
  /// Android-only. On other platforms the native side returns 0 and this
  /// throws a [StateError] with the underlying error message.
  ///
  /// Requirements:
  /// - [device] was created on the Vulkan backend with
  ///   `VK_ANDROID_external_memory_android_hardware_buffer` enabled.
  /// - [ahbPtr] is a valid `AHardwareBuffer*`. The native side performs its
  ///   own `AHardwareBuffer_acquire` so the caller can release its reference
  ///   immediately after this returns.
  /// - The AHB's descriptor must match [width]/[height], have a single layer,
  ///   include `AHARDWAREBUFFER_USAGE_GPU_SAMPLED_IMAGE`, and its format must
  ///   map to [format] (currently `Rgba8Unorm` or `Rgba16Float`).
  ///
  /// The returned texture has usage = `TEXTURE_BINDING | COPY_SRC`.
  factory WgpuTexture.fromAHardwareBuffer(
    WgpuDevice device,
    Pointer<Void> ahbPtr,
    GpuTextureFormat format,
    int width,
    int height, {
    String label = '',
  }) {
    if (ahbPtr == nullptr) {
      throw ArgumentError.value(ahbPtr, 'ahbPtr', 'must not be null');
    }
    if (width <= 0) throw ArgumentError.value(width, 'width', 'must be positive');
    if (height <= 0) {
      throw ArgumentError.value(height, 'height', 'must be positive');
    }
    final handle = _wgpunDeviceImportAHardwareBuffer(
      device.handle,
      ahbPtr,
      width,
      height,
      format.ffiValue,
    );
    if (handle == 0) {
      throw StateError(
        'Failed to import AHardwareBuffer: ${wgpuLastError()}',
      );
    }
    return WgpuTexture.internal(
      handle,
      width: width,
      height: height,
      depthOrArrayLayers: 1,
      dimension: GpuTextureDimension.d2,
      format: format,
      usage: GpuTextureUsage.textureBinding | GpuTextureUsage.copySrc,
      mipLevelCount: 1,
      sampleCount: 1,
      label: label,
    );
  }

  /// Creates a view into this texture.
  @override
  WgpuTextureView createView({
    GpuTextureFormat? format,
    GpuTextureViewDimension? dimension,
    GpuTextureUsageFlags? usage,
    int baseMipLevel = 0,
    int? mipLevelCount,
    int baseArrayLayer = 0,
    int? arrayLayerCount,
    GpuTextureAspect aspect = GpuTextureAspect.all,
    String swizzle = 'rgba',
    String label = '',
  }) {
    if (isDisposed) throw StateError('Texture already disposed');

    final hasDescriptor =
        format != null ||
        dimension != null ||
        usage != null ||
        baseMipLevel != 0 ||
        mipLevelCount != null ||
        baseArrayLayer != 0 ||
        arrayLayerCount != null ||
        aspect != GpuTextureAspect.all;

    if (!hasDescriptor) {
      final viewHandle = ffi.wgpun_TextureCreateView(nativeHandle, nullptr);
      if (viewHandle == 0) {
        throw StateError('Failed to create texture view: ${wgpuLastError()}');
      }
      return WgpuTextureView.internal(viewHandle, label: label);
    }

    return using((arena) {
      final desc = arena<ffi.WGPUTextureViewDescriptor>();
      desc.ref.format = (format ?? this.format).ffiValue;
      desc.ref.dimension = (dimension ?? GpuTextureViewDimension.d2).ffiValue;
      desc.ref.base_mip_level = baseMipLevel;
      desc.ref.mip_level_count = mipLevelCount ?? 0;
      desc.ref.base_array_layer = baseArrayLayer;
      desc.ref.array_layer_count = arrayLayerCount ?? 0;
      desc.ref.aspect = aspect.ffiValue;
      desc.ref.usage = usage ?? 0;
      if (label.isNotEmpty) {
        desc.ref.label = label.toNativeUtf8(allocator: arena).cast();
      }

      final viewHandle = ffi.wgpun_TextureCreateView(nativeHandle, desc);
      if (viewHandle == 0) {
        throw StateError('Failed to create texture view: ${wgpuLastError()}');
      }
      return WgpuTextureView.internal(viewHandle, label: label);
    });
  }

  @override
  void destroy() => dispose();
}

/// A view into a texture.
class WgpuTextureView extends WgpuNativeResource implements GpuTextureView {
  static final _fin = NativeFinalizer(
    Native.addressOf<NativeFunction<Void Function(Pointer<Void>)>>(
      ffi.wgpun_TextureViewRelease_p,
    ),
  );

  @override
  String label;

  WgpuTextureView.internal(int handle, {this.label = ''}) : super(handle, _fin);

  int get handle => nativeHandle;

  @override
  NativeFinalizer get finalizer => _fin;
  @override
  void release(int handle) => ffi.wgpun_TextureViewRelease(handle);
}
